/* Text-first Lavender Notebook: pure social feed on / and owner-only post management on /admin. */
const KEY='lavender-notebook-posts';
let posts=JSON.parse(localStorage.getItem(KEY)||'[]');
let liked=JSON.parse(localStorage.getItem('lavender-notebook-liked')||'{}');
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
function heart(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 8.8c0 5.4-8.8 10.1-8.8 10.1S3.2 14.2 3.2 8.8A4.7 4.7 0 0 1 12 6.5a4.7 4.7 0 0 1 8.8 2.3Z"/></svg>'}
function header(){return `<header class="topbar"><div class="topbar-inner"><a class="brand" href="/" aria-label="Lavender Notebook feed"><span class="brand-mark">LN</span><span class="brand-word">lavender<small>notebook</small></span></a><nav class="nav-actions"><a class="nav-link active" href="/">Feed</a><a class="nav-link" href="/admin">Admin</a></nav></div></header>`}
function postCard(post,admin=false){return `<article class="post"><div class="post-head"><div class="avatar">LN</div><div class="post-meta"><strong>lavender notebook</strong><span>${esc(post.date)} · public</span></div>${admin?`<button class="delete-button" onclick="deletePost('${post.id}')" aria-label="Delete post">Delete</button>`:''}</div><div class="post-body"><p class="caption">${esc(post.caption)}</p></div><div class="post-foot"><span class="post-count">${post.likes||0} likes</span><button class="like-button ${liked[post.id]?'liked':''}" onclick="toggleLike('${post.id}',this)" aria-label="${liked[post.id]?'Unlike':'Like'} post">${heart()}<span>Like</span></button></div></article>`}
function home(){app.innerHTML=`<div class="site-shell">${header()}<main class="feed-page"><div class="feed-toolbar"><div><span class="eyebrow">Public feed</span><h1>Recent posts</h1></div><a class="primary compact" href="/admin">＋ New post</a></div><div class="feed">${posts.length?posts.map(postCard).join(''):`<div class="empty"><div class="empty-mark">＋</div><h2>No posts yet.</h2><p>There is nothing here until the owner adds the first note.</p></div>`}</div></main><div class="toast" id="toast"></div></div>`}
function adminGate(){app.innerHTML=`<div class="site-shell">${header()}<main class="studio-page"><section class="studio-card gate-card"><span class="eyebrow">Owner access</span><h1>Admin</h1><p>This page is only for the notebook owner.</p><form onsubmit="unlock(event)"><div class="field"><label for="pass">Private passcode</label><input id="pass" type="password" autocomplete="current-password" placeholder="Enter passcode" required /></div><button class="primary" type="submit">Enter admin</button></form><p class="footnote">Supabase Auth will replace this local gate for production access.</p></section></main></div>`}
function unlock(e){e.preventDefault();if(document.getElementById('pass').value!=='notebook'){toast('Incorrect passcode.');return}sessionStorage.setItem('ln-admin','1');admin()}
function admin(){if(sessionStorage.getItem('ln-admin')!=='1'){adminGate();return}app.innerHTML=`<div class="site-shell">${header()}<main class="studio-page"><section class="studio-card"><div class="studio-top"><div><span class="eyebrow">Owner access</span><h1>Admin</h1><p>Create and manage text posts for the public feed.</p></div><div class="admin-actions"><button class="secondary" onclick="logoutAdmin()">Lock</button><a class="secondary" href="/">View feed</a></div></div><form onsubmit="createPost(event)" class="composer"><div class="field"><label for="new-caption">Post text</label><textarea id="new-caption" placeholder="Write a caption or note..." required></textarea></div><div class="field"><label for="new-date">Date label</label><input id="new-date" type="text" value="${new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}" required /></div><button class="primary" type="submit">Publish post</button></form></section><section class="admin-list"><div class="list-heading"><span class="eyebrow">Published</span><strong>${posts.length} ${posts.length===1?'post':'posts'}</strong></div>${posts.length?posts.map(p=>postCard(p,true)).join(''):`<div class="empty small"><p>Your published posts will appear here.</p></div>`}</section></main><div class="toast" id="toast"></div></div>`}
function createPost(e){e.preventDefault();const caption=document.getElementById('new-caption').value.trim();const date=document.getElementById('new-date').value.trim();if(!caption)return;posts.unshift({id:'p'+Date.now(),caption,date,likes:0});localStorage.setItem(KEY,JSON.stringify(posts));toast('Post published.');setTimeout(admin,500)}
function deletePost(id){if(!confirm('Delete this post?'))return;posts=posts.filter(p=>p.id!==id);delete liked[id];localStorage.setItem(KEY,JSON.stringify(posts));localStorage.setItem('lavender-notebook-liked',JSON.stringify(liked));admin()}
function logoutAdmin(){sessionStorage.removeItem('ln-admin');location.href='/admin'}
function toggleLike(id,btn){let post=posts.find(p=>p.id===id);if(!post)return;if(liked[id]){post.likes=Math.max(0,(post.likes||0)-1);delete liked[id]}else{post.likes=(post.likes||0)+1;liked[id]=true}localStorage.setItem(KEY,JSON.stringify(posts));localStorage.setItem('lavender-notebook-liked',JSON.stringify(liked));btn.classList.toggle('liked',!!liked[id]);btn.closest('.post').querySelector('.post-count').textContent=`${post.likes} likes`}
function toast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2000)}
Object.assign(window,{unlock,admin,adminGate,createPost,deletePost,logoutAdmin,toggleLike});
if(location.pathname==='/admin')admin();else home();
