/* Lavender Notebook: Supabase-backed feed, public likes, and owner media publishing. */
const SUPABASE_URL='__SUPABASE_URL__';
const SUPABASE_ANON_KEY='__SUPABASE_ANON_KEY__';
const OWNER_EMAIL='yeshlieashrevie@gmail.com';
const STORAGE_BUCKET='media';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const app=document.getElementById('app');
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const visitorId=(()=>{let id=localStorage.getItem('ln-visitor-id');if(!id){id=crypto.randomUUID();localStorage.setItem('ln-visitor-id',id)}return id})();
let selectedFiles=[];let selectedLayout='carousel';
function heart(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 8.8c0 5.4-8.8 10.1-8.8 10.1S3.2 14.2 3.2 8.8A4.7 4.7 0 0 1 12 6.5a4.7 4.7 0 0 1 8.8 2.3Z"/></svg>'}
function header(){return `<header class="topbar"><div class="topbar-inner"><a class="brand" href="/" aria-label="Lavender Notebook feed"><span class="brand-mark">LN</span><span class="brand-word">lavender<small>notebook</small></span></a><nav class="nav-actions"><a class="nav-link active" href="/">Feed</a></nav></div></header>`}
function publicMedia(post){if(!post.media?.length)return '';if(post.layout==='reel')return `<div class="reel-frame"><video src="${post.media[0].url}" controls playsinline preload="metadata"></video><span class="media-badge">reel</span></div>`;if(post.media.length===1)return `<div class="media-frame"><img src="${post.media[0].url}" alt="Post image" loading="lazy"/></div>`;return `<div class="carousel" data-index="0">${post.media.map((m,i)=>`<div class="media-frame ${i===0?'active':''}"><img src="${m.url}" alt="Carousel image ${i+1}" loading="lazy"/></div>`).join('')}<button class="carousel-arrow prev" onclick="moveCarousel(this,-1)" aria-label="Previous image">‹</button><button class="carousel-arrow next" onclick="moveCarousel(this,1)" aria-label="Next image">›</button><div class="carousel-dots">${post.media.map((_,i)=>`<button class="dot ${i===0?'active':''}" onclick="jumpCarousel(this,${i})" aria-label="Go to image ${i+1}"></button>`).join('')}</div></div>`}
async function loadPosts(){if(!sb)return{posts:[],error:'Supabase configuration is missing.'};const {data,error}=await sb.from('posts').select('id,caption,published_at,created_by,layout').order('published_at',{ascending:false});if(error)return{posts:[],error:error.message};if(!data?.length)return{posts:[],error:null};const ids=data.map(p=>p.id);const [likes,media]=await Promise.all([sb.from('post_likes').select('post_id,visitor_id').in('post_id',ids),sb.from('post_media').select('post_id,storage_path,media_type,sort_order').in('post_id',ids).order('sort_order')]);const counts={};const mine={};(likes.data||[]).forEach(l=>{counts[l.post_id]=(counts[l.post_id]||0)+1;if(l.visitor_id===visitorId)mine[l.post_id]=true});const grouped={};(media.data||[]).forEach(m=>{const url=sb.storage.from(STORAGE_BUCKET).getPublicUrl(m.storage_path).data.publicUrl;(grouped[m.post_id]??=[]).push({url,type:m.media_type})});return{posts:data.map(p=>({...p,likes:counts[p.id]||0,liked:!!mine[p.id],media:grouped[p.id]||[]})),error:null}}
function postCard(post,admin=false){const date=new Date(post.published_at).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});return `<article class="post"><div class="post-head"><div class="avatar">LN</div><div class="post-meta"><strong>lavender notebook</strong><span>${esc(date)} · public</span></div>${admin?`<button class="delete-button" onclick="deletePost('${post.id}')" aria-label="Delete post">Delete</button>`:''}</div>${publicMedia(post)}<div class="post-body"><p class="caption">${esc(post.caption)}</p></div><div class="post-foot"><span class="post-count">${post.likes||0} likes</span><button class="like-button ${post.liked?'liked':''}" onclick="toggleLike('${post.id}',this)" aria-label="${post.liked?'Unlike':'Like'} post">${heart()}<span>Like</span></button></div></article>`}
async function home(){app.innerHTML=`<div class="site-shell">${header()}<main class="feed-page"><div class="feed-toolbar"><div><span class="eyebrow">Public feed</span><h1>Recent posts</h1></div></div><div class="feed"><div class="empty"><p>Loading posts…</p></div></div></main><div class="toast" id="toast"></div></div>`;const result=await loadPosts();const feed=document.querySelector('.feed');if(result.error){feed.innerHTML=`<div class="empty"><h2>Feed unavailable.</h2><p>${esc(result.error)}</p></div>`;return}feed.innerHTML=result.posts.length?result.posts.map(postCard).join(''):`<div class="empty"><div class="empty-mark">＋</div><h2>No posts yet.</h2><p>There is nothing here until the owner publishes the first note.</p></div>`}
function adminGate(message=''){app.innerHTML=`<div class="site-shell">${header()}<main class="studio-page"><section class="studio-card gate-card"><span class="eyebrow">Owner access</span><h1>Admin</h1><p>Sign in with the owner account to publish posts.</p>${message?`<div class="error-message">${esc(message)}</div>`:''}<form onsubmit="unlock(event)"><div class="field"><label for="email">Owner email</label><input id="email" type="email" value="${OWNER_EMAIL}" autocomplete="username" required /></div><div class="field"><label for="pass">Password</label><input id="pass" type="password" autocomplete="current-password" placeholder="Supabase Auth password" required /></div><button class="primary" type="submit">Sign in</button></form><p class="footnote">Authentication is handled by Supabase Auth.</p></section></main></div>`}
async function unlock(e){e.preventDefault();if(!sb){adminGate('Supabase configuration is missing.');return}const email=document.getElementById('email').value.trim();const password=document.getElementById('pass').value;const {error}=await sb.auth.signInWithPassword({email,password});if(error){adminGate(error.message);return}admin()}
async function admin(){if(!sb){adminGate('Supabase configuration is missing.');return}const {data:{session}}=await sb.auth.getSession();if(!session){adminGate();return}const result=await loadPosts();selectedFiles=[];selectedLayout='carousel';app.innerHTML=`<div class="site-shell">${header()}<main class="studio-page"><section class="studio-card"><div class="studio-top"><div><span class="eyebrow">Owner access</span><h1>Admin</h1><p>Publish photos as a carousel or one video as a reel.</p></div><div class="admin-actions"><button class="secondary" onclick="logoutAdmin()">Lock</button><a class="secondary" href="/">View feed</a></div></div><form onsubmit="createPost(event)" class="composer"><label class="dropzone" for="media-input"><span><strong>Choose photos or a video</strong>Photos: up to 8 · Reel: one video · 50 MB max each</span><input id="media-input" type="file" accept="image/*,video/*" multiple onchange="previewFiles(event)"/></label><div class="preview-strip" id="preview-strip"></div><div class="field"><label>Post format</label><div class="option-row"><button type="button" class="layout-option selected" data-layout="carousel" onclick="chooseLayout(this)">Instagram carousel</button><button type="button" class="layout-option" data-layout="reel" onclick="chooseLayout(this)">Reel / video</button></div></div><div class="field"><label for="new-caption">Caption</label><textarea id="new-caption" placeholder="Write a caption or note..." required></textarea></div><button class="primary" type="submit">Publish post</button></form></section><section class="admin-list"><div class="list-heading"><span class="eyebrow">Published</span><strong>${result.posts.length} ${result.posts.length===1?'post':'posts'}</strong></div>${result.posts.length?result.posts.map(p=>postCard(p,true)).join(''):`<div class="empty small"><p>Your published posts will appear here.</p></div>`}</section></main><div class="toast" id="toast"></div></div>`}
function chooseLayout(btn){document.querySelectorAll('.layout-option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');selectedLayout=btn.dataset.layout;const input=document.getElementById('media-input');if(input){input.value='';input.multiple=selectedLayout!=='reel';selectedFiles=[];document.getElementById('preview-strip').innerHTML=''}}
function previewFiles(e){let files=[...e.target.files];if(selectedLayout==='reel')files=files.filter(f=>f.type.startsWith('video')).slice(0,1);else files=files.filter(f=>f.type.startsWith('image')).slice(0,8);selectedFiles=files;document.getElementById('preview-strip').innerHTML=files.map(f=>{const u=URL.createObjectURL(f);return f.type.startsWith('video')?`<video src="${u}" controls muted></video>`:`<img src="${u}" alt="Preview"/>`}).join('')}
async function createPost(e){e.preventDefault();const caption=document.getElementById('new-caption').value.trim();if(!selectedFiles.length||!caption){toast('Choose media and add a caption first.');return}if(selectedLayout==='reel'&&!selectedFiles[0].type.startsWith('video')){toast('Choose one video for a reel.');return}const {data:{user}}=await sb.auth.getUser();if(!user){adminGate('Your session expired.');return}const {data:post,error:postError}=await sb.from('posts').insert({caption,layout:selectedLayout,created_by:user.id}).select('id').single();if(postError){toast(postError.message);return}const mediaRows=[];for(let i=0;i<selectedFiles.length;i++){const file=selectedFiles[i];const safeName=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const storagePath=`${user.id}/${post.id}/${i}-${safeName}`;const upload=await sb.storage.from(STORAGE_BUCKET).upload(storagePath,file,{contentType:file.type,upsert:false});if(upload.error){await sb.from('posts').delete().eq('id',post.id);toast(upload.error.message);return}mediaRows.push({post_id:post.id,storage_path:storagePath,media_type:file.type.startsWith('video')?'video':'image',sort_order:i})}const {error:mediaError}=await sb.from('post_media').insert(mediaRows);if(mediaError){await sb.from('posts').delete().eq('id',post.id);toast(mediaError.message);return}toast('Post published.');setTimeout(admin,700)}
async function deletePost(id){if(!confirm('Delete this post?'))return;const {error}=await sb.from('posts').delete().eq('id',id);if(error){toast(error.message);return}admin()}
async function logoutAdmin(){await sb.auth.signOut();location.href='/admin.html'}
async function toggleLike(id,btn){const liked=btn.classList.contains('liked');const response=liked?await sb.from('post_likes').delete().eq('post_id',id).eq('visitor_id',visitorId):await sb.from('post_likes').insert({post_id:id,visitor_id:visitorId});if(response.error){toast(response.error.message);return}btn.classList.toggle('liked',!liked);const count=btn.closest('.post').querySelector('.post-count');const n=parseInt(count.textContent)||0;count.textContent=`${Math.max(0,n+(liked?-1:1))} likes`}
function carouselState(root,index){const frames=root.querySelectorAll('.media-frame'),dots=root.querySelectorAll('.dot');index=(index+frames.length)%frames.length;frames.forEach((f,i)=>f.classList.toggle('active',i===index));dots.forEach((d,i)=>d.classList.toggle('active',i===index));root.dataset.index=index}
function moveCarousel(btn,dir){const root=btn.closest('.carousel');carouselState(root,Number(root.dataset.index)+dir)}
function jumpCarousel(btn,index){carouselState(btn.closest('.carousel'),index)}
function toast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
Object.assign(window,{unlock,admin,adminGate,createPost,deletePost,logoutAdmin,toggleLike,previewFiles,chooseLayout,moveCarousel,jumpCarousel});
if(location.pathname==='/admin'||location.pathname==='/admin.html')admin();else home();
